- name: Get ovirt_auth token
  ovirt_auth:
    url: "{{ ovirt_url }}"
    username: "{{ ovirt_user }}"
    ca_file: "{{ ovirt_ca }}"
    password: "{{ ovirt_password }}"

- name: Create VM
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: running
    name: "{{ item.key }}.{{ domain }}"
    cluster: "{{ ovirt_cluster }}"
    template: "{{ item.value.template }}"
    memory: "{{ item.value.memory }}"
    cpu_cores: "{{ item.value.cpu_cores }}"
    cpu_sockets: "{{ item.value.cpu_sockets }}"
    cpu_threads: "{{ item.value.cpu_threads }}"
    type: server
    ballooning_enabled: false
    wait: yes
    memory_guaranteed: "{{ item.value.memory_guaranteed }}"
    memory_max: "{{ item.value.memory_max }}"
    fetch_nested: true
    cloud_init_nics:
      - nic_name: "{{ item.value.fe_nic }}"
        nic_ip_address: "{{ public_cidr | ipaddr('net') | ipaddr(item.value.ip_offset) | ipaddr('address') }}"
        nic_netmask: "{{ public_cidr | ipaddr('netmask') }}"
        nic_gateway: "{{ public_cidr | ipaddr('net') | ipaddr('1') | ipaddr('address') }}"
        nic_on_boot: true
        nic_boot_protocol: static
      - nic_name: "{{ item.value.be_nic }}"
        nic_ip_address: "{{ private_cidr | ipaddr('net') | ipaddr(item.value.ip_offset) | ipaddr('address') }}"
        nic_netmask: "{{ public_cidr | ipaddr('netmask') }}"
        nic_on_boot: true
        nic_boot_protocol: static
    cloud_init:
      host_name: "{{ item.key }}.{{ item.value.domain | default(domain) }}"
      authorized_ssh_keys: "{{ item.value.gpte_key | default(gpte_key) }}"
      user_name: root
      root_password: "{{ item.value.root_password | default(root_password) }}"
      dns_servers: "{{ item.value.dns_servers | default(dns_servers) }}"
      regenerate_ssh_keys: true
  register: instance_details

- debug:
    msg: "{{ instance_details.vm.disk_attachments[0].id }}"

- name: Stopping instance before resize the disk
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: stopped
    name: "{{ item.key }}.{{ domain }}"
  register: r_stopped
  when: instance_details.changed

- name: Increase root disk size
  ovirt_disk:
    auth: "{{ ovirt_auth }}"
    id: "{{ instance_details.vm.disk_attachments[0].id }}"
    size: "{{ item.value.root_disk_size }}"
    wait: true
    vm_name: "{{ item.key }}.{{ domain }}"
    bootable: true
  when: instance_details.changed

- name: Stopping instance before resize the disk
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: running
    name: "{{ item.key }}.{{ domain }}"
  when: r_stopped.changed

- name: Include host in inventory
  add_host:
    name: "{{ public_cidr | ipaddr('net') | ipaddr(item.value.ip_offset) | ipaddr('address') }}"
    groups:
      - new_vms
      - "{{ item.value.group }}"
    new_host_name: "{{ item.key }}.{{ domain }}"


