# - name: Reboot the server
#   reboot:
#     connect_timeout: 300
#     reboot_timeout: 300

- name: Gather facts once host is reachable
  setup:

- name: Update network manager connection profile with routes
  command: |
    /usr/bin/nmcli connection modify "System eth1" +ipv4.routes  "{{ item }} {{ private_cidr | ipaddr('net') | ipaddr('1') | ipaddr('address') }}"
  loop:
    - 10.0.0.0/8
    - 161.26.0.0/16
    - 166.8.0.0/14

- name: Use nmcli to install the configured routes
  command: '/usr/bin/nmcli connection up "System eth1"'


- name: Disable interactive logins via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Check subscription-manager status
  shell: "/sbin/subscription-manager status"
  register: sm_status

- name: Register with Satellite
  block:

  - name: Install Satellite CA
    package:
     name: http://{{ rhsm_server_hostname }}/pub/katello-ca-consumer-latest.noarch.rpm
     state: present
    when:
     - "'not registered' in rh_subscribed.stdout"

  - name: Subscribe to CDN
    import_role:
     name: oasis_roles.system.rhsm
    vars:
     rhsm_org_id: "{{ rhsm_org_id }}"
     rhsm_activationkey: "{{ rhsm_activationkey }}"
     rhsm_server_hostname: "{{ rhsm_server_hostname }"
     rhsm_force_register: true
     rhsm_repositories:
       enabled:
         - '*'

  become: true
  ignore_errors: yes
  when: sm_status.rc != 0

- name: Set chrony
  vars:
    chrony_servers:
      - servertime.service.softlayer.com
  import_role:
    name: oasis_roles.system.chrony

- name: Enable and restart chrony
  systemd:
    name: chronyd
    enabled: yes
    state: started

- name: Install common packages
  package:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
      - bash-completion
      - chrony
      - git
      - tmux
      - tree
      - vim
      - wget
      - tcpdump
      - sysstat
      - katello-agent

- name: Include ssh ports and firewall
  include: register-idm.yaml

- name: Include ssh ports and firewall
  include: ssh-ports.yaml
